### ISSUE TITLE
Add support for missing transformations

### ISSUE THREAD

**Issue by alijdens** [alijdens/spark-board#22]
We are not considering the following transformations:

1. Union and its variants like `unionAll`, `subtract` (which is `except` in Spark`), etc
2. Limit, which Spark parses to `GlobalLimit` and `LocalLimit` (which I believe are just implementations, so we can just consider a single `Limit` transformation).
3. A bun of other transformations have `TODO`s that we should finish too.

**Comment by eze210** [comment]
Also, add a Unknown transformation type and a WARN when we don't recognize a transformation in the job
