### ISSUE TITLE
Column origins are not being tracked beyond aggregations

### ISSUE THREAD

**Issue by alijdens** [alijdens/spark-board#36]
When a column is the product of an aggregation (`groupBy`), the column tracking stops there instead of showing which are the columns that were part of the operation.

Here's an example from `mix.py`

![image](https://github.com/alijdens/spark-board/assets/63980668/b1f9e356-fbe6-4231-a97f-2489688a8eaa)

Note that multiple columns could be used to create a single column in an aggregation (like when doing a weighted average for example)

**Comment by eze210** [comment]
Fixed by #48
