### ISSUE TITLE
Handle unknown transformations

### ISSUE THREAD

**Issue by alijdens** [alijdens/spark-board#51]
It may happen that future spark releases add new transformations. If that happens, the script will fail and the user is left with nothing. To avoid this from happening, we could handle this type of scenarios by creating an `Unknown` type that collects some generic node information and is shown with a `?` in the UI.

In this way, we would at least let the user explore the parts of the DAG that were properly generated (and what data is avaialble for the unknown nodes) instead of not delivering anything at all.

**Comment by eze210** [comment]
JS world: throw exception
Python world: add an unknown node
